name: Build and Deploy MeshSpace to EC2

on:
  push:
    branches:
      - future-deploy  # or your preferred branch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker build -t meshspace-backend ./meshspace-backend
          docker build -t meshspace-frontend ./meshspace-frontend

      - name: Save Docker images as tarballs
        run: |
            docker save meshspace-backend -o backend.tar
            docker save meshspace-frontend -o frontend.tar
            chmod 644 backend.tar frontend.tar
        

      - name: Copy Docker images to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend.tar,frontend.tar"
          target: "/home/${{ secrets.EC2_USER }}/meshspace"

      - name: SSH into EC2 and load + run containers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install Docker if missing
            if ! command -v docker &> /dev/null; then
                sudo apt update -y
                sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
                echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
                sudo apt update -y
                sudo apt install -y docker-ce docker-ce-cli containerd.io
                sudo usermod -aG docker ubuntu
                sudo systemctl start docker
                sudo systemctl enable docker
            fi

            cd meshspace
            docker load -i backend.tar
            docker load -i frontend.tar

            docker stop backend || true && docker rm backend || true
            docker stop frontend || true && docker rm frontend || true

            docker run -d --name backend -p 5100:5100 meshspace-backend
            docker run -d --name frontend -p 4173:4173 meshspace-frontend


